version: "3.5"

services:
    liuwei:
        image: tkpdx01/heihei:latest
        container_name: lgq_xx
        # 自动重启
        restart: always
        network_mode: bridge
        # 挂载目录
        volumes:
            - /opt/xuexi/user:/xuexi/user
            #- /opt/xuexi/static:/xuexi/static
            #- /opt/xuexi/pdlearn:/xuexi/pdlearn
        # 打开的端口
        ports:
            # 打开30080端口，访问 http://服务器ip:30080 进行控制
            # 这个30081端口对应容器内8088是微信公众号控制端口，我预先映射出来了，免得你们再去查找
            - 30080:80
            - 30081:8088
        # 设置共享内存2g（shared memory）,减少chrome崩溃
        shm_size: 4gb
        # 环境变量
        environment:
            # 将在每天5：47和13：47及21：47自动运行一次学习，防止忘记点UID开始学习
            - CRONTIME=10 8,15 * * *
            # 打开专项答题
            - ZhuanXiang=True
            # 信息推送模式：网页模式
            - Pushmode=1
            # 以下爱参数网页模式不需要，其他模式请根据实际情况修改
            # - "AccessToken={token}"
            # - "Secret={密钥}"
            - AccessToken=c0772400ec972bb29bbd26c99034b0f17acb5aefcf3db2255408da1881c73c6b
            - Secret=SEC8d5a58292005bb4ca1b3dfbd73eeb36bf7611b40ae0c1956f5a6d9d39cf61085
            - Scheme=dtxuexi://appclient/page/study_feeds?url=